"""Initial migration.

Revision ID: 557c37df625a
Revises: 
Create Date: 2021-10-25 21:23:07.323324

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "557c37df625a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
